добавляет базовую стилизацию мобильных версий страниц
htmlacademy-adaptive/1250645-mishka-1 pull request #3
Opened 2023-09-06 14:43 UTC by bga87

2023-09-06 16:11 UTC, Kartaviy-arteom requested changes

2023-09-06 16:11 UTC, Kartaviy-arteom commented on source/js/app.js
> +modalShowButton.addEventListener("click", showModal);
тут у тебя оинаковый js на всех страницах, а элемент этот есть не на каждой странице. И твой js будет падать с TypeError, так как modalShowButton будет null. Ты можешь использовать удобный синтаксис [опциональных цепочек](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Optional_chaining ) для проверки на существование. В других скриптах аналогично

2023-09-06 16:11 UTC, Kartaviy-arteom commented on source/sass/header.scss
> +  font-family: "Open Sans", sans-serif;
https://up.htmlacademy.ru/adaptive-individual/1/criteries#b10

2023-09-06 16:11 UTC, Kartaviy-arteom commented on source/sass/style.scss
> +@use "visually-hidden";
посмотри этот критерий https://up.htmlacademy.ru/adaptive-individual/1/criteries#b13 . Тут нужно вынести блоки в отдельную директорию. Для общих стилей ты можешь создать дирректорию common для подключения шрифтов, переменных и тд

2023-09-06 16:11 UTC, Kartaviy-arteom commented on source/sass/hero.scss
> +    background-color: #56c3b2;
попробуй использовать переменные для повторяющихся значений, это упрощает изменения в будующем, хоть в учебном проекте их и не предвидится

2023-09-06 16:11 UTC, Kartaviy-arteom commented on source/index.html
> +        <div class="feedback__wrapper slider">
тут у тебя есть компонент слайдер, который при этом элемент блока feedback, но зачем элементам слайдера быть еще и элементами feedback. Они просто элементы слайдера. Элемент слайдера не должен "знать" что он находится где-то кроме слайдера, у него один родительский блок. "feedback__list slider__list" станет просто "slider__list" и тд

2023-09-07 00:23 UTC, bga87 commented on source/js/app.js
> +modalShowButton.addEventListener("click", showModal);
Поправил

2023-09-07 00:39 UTC, bga87 commented on source/sass/style.scss
> +@use "visually-hidden";
Привел в соответствие

2023-09-07 02:57 UTC, bga87 commented on source/sass/hero.scss
> +    background-color: #56c3b2;
вынес некоторые цвета в общий модуль variables

2023-09-07 03:09 UTC, bga87 commented on source/index.html
> +        <div class="feedback__wrapper slider">
отрефакторил

2023-09-07 12:12 UTC, merged